stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/cardata.csv
    outs:
    - data/raw/cardata.csv

  clean_data:
    cmd: python src/clean_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data/raw/cardata.csv
    outs:
    - data/clean/cardata.csv
    
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/clean/cardata.csv
    outs:
    - data/processed/train_cardata.csv
    - data/processed/test_cardata.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_cardata.csv
    - data/processed/test_cardata.csv
    - src/train_and_evaluate.py
    metrics:
    - report/scores.json:
        cache: false
    outs:
    - saved_models/model.joblib

    