base:
  project: car_price-project
  random_state: 42
  target_col: Selling_Price

data_source:
  s3_source: data_given/cardata.csv

load_data:
  raw_dataset_csv: data/raw/cardata.csv

clean_data:
  clean_dataset_csv: data/clean/cardata.csv

split_data:
  train_path: data/processed/train_cardata.csv
  test_path: data/processed/test_cardata.csv
  test_size: 0.3

models:

  estimators:
    model_type: XGBRegressor

model_dir: saved_models

reports:
  scores: report/scores.json